name: SWC

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

env:
  CARGO_INCREMENTAL: 0

jobs:
  fmt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: swc
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: swc
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy
      - name: Check
        run: cargo clippy --all
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: swc
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-wasi
      - name: Run cargo check
        run: cargo check
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: swc
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-wasi
      - name: Run cargo test
        run: cargo test --color always